// Yangi restoran uchun boshlang'ich (demo) sozlamalar.
// Admin panelda o'zgartirilgan sozlamalar realtime kanal orqali barcha qurilmalarga tarqaladi.
export const DEFAULT_CONFIG = {
  v: 3,
  updatedAt: 0,
  restaurant: {
    name: "Demo Restoran",
    slogan: "Milliy taomlar, samimiy xizmat",
    logo: "",
    color: "#B4232A",
    currency: "so'm",
    service: 10,
    address: "Toshkent sh., Amir Temur ko'chasi, 1",
    phone: "+998 90 123 45 67"
  },
  categories: [
    { id: "hot", name: "Issiq taomlar", tagline: "olovdan to'g'ri dasturxonga", emoji: "🔥", bg: "img/m/bg-hot.jpg", hero: "img/m/lamb-rack.jpg" },
    { id: "milliy", name: "Milliy taomlar", tagline: "an'anaviy o'zbek oshxonasi", emoji: "🍲", bg: "img/m/bg-milliy.jpg", hero: "img/m/veal-stew.jpg" },
    { id: "pasta", name: "Rizotto va pasta", tagline: "Italiya ruhida", emoji: "🍝", bg: "img/m/bg-pasta.jpg", hero: "img/m/risotto.jpg" },
    { id: "salad", name: "Salatlar", tagline: "yengil va yangi", emoji: "🥗", bg: "img/m/bg-salad.jpg", hero: "img/m/sunomono.jpg" },
    { id: "sushi", name: "Sushi va rollar", tagline: "yapon an'anasi", emoji: "🍣", bg: "img/m/bg-sushi.jpg", hero: "img/m/black-roll.jpg" },
    { id: "ramen", name: "Ramen", tagline: "issiq va to'yimli", emoji: "🍜", bg: "img/m/bg-ramen.jpg", hero: "img/m/ramen3.jpg" },
    { id: "dessert", name: "Desertlar", tagline: "shirin yakun", emoji: "🍰", bg: "img/m/bg-dessert.jpg", hero: "img/m/dessert2.jpg" },
    { id: "cocktail", name: "Kokteyllar", tagline: "kechki kayfiyat uchun", emoji: "🍸", bg: "img/m/bg-cocktail.jpg", hero: "img/m/negroni.jpg", adult: true },
    { id: "wine", name: "Vinolar", tagline: "Italiya uzumzorlaridan", emoji: "🍷", bg: "img/m/bg-wine.jpg", hero: "img/m/wine-hand.jpg", adult: true },
    { id: "drinks", name: "Choy va ichimliklar", tagline: "salqin va iliq", emoji: "🫖", bg: "img/m/bg-drinks.jpg", hero: "img/m/mojito.jpg" }
  ],
  items: [
    { id: "h1", cat: "hot", name: "Mol go'shti steyki", desc: "Grilda pishirilgan steyk, sabzavotlar va qora murch sousi bilan.", price: 145000, img: "img/m/steak-veg.jpg", popular: true, time: 20, weight: "300 g", variants: [{ id: "rare", name: "Qonli", price: 145000 }, { id: "medium", name: "O'rtacha", price: 145000 }, { id: "well", name: "To'liq pishgan", price: 145000 }], extras: [{ id: "mush", name: "Qo'ziqorin sousi", price: 12000 }, { id: "cheese", name: "Pishloq sousi", price: 12000 }, { id: "fries", name: "Fri kartoshka", price: 18000 }] },
    { id: "h2", cat: "hot", name: "Qo'zi qovurg'asi", desc: "Grilda qo'zi qovurg'asi, pishirilgan sarimsoq va grill sabzavotlar.", price: 165000, img: "img/m/lamb-rack.jpg", popular: true, time: 25, weight: "250 g" },
    { id: "h3", cat: "hot", name: "Filet minyon", desc: "Mol go'shti filesi, roti sousi va rustik kartoshka.", price: 175000, img: "img/m/filet.jpg", time: 20, weight: "220 g" },
    { id: "h4", cat: "hot", name: "Grilda losos", desc: "Losos filesi, sariyog'li sabzavotlar va limonli guruch.", price: 135000, img: "img/m/salmon-grill.jpg", time: 18, weight: "200 g" },
    { id: "h5", cat: "hot", name: "Tandir losos", desc: "Ziravorli qobiqda pishirilgan losos, yangi ko'katlar bilan.", price: 129000, img: "img/m/salmon.jpg", time: 18, weight: "200 g" },
    { id: "h6", cat: "hot", name: "Tovuq grill", desc: "Marinadlangan tovuq, fri kartoshka, koulslou va jigarrang sous.", price: 68000, img: "img/m/chicken-grill.jpg", time: 20 },
    { id: "h7", cat: "hot", name: "Tovuq chop", desc: "Qarsildoq qobiqdagi tovuq, fri kartoshka va koulslou.", price: 68000, img: "img/m/chicken-chop.jpg", time: 18 },
    { id: "h8", cat: "hot", name: "Tovuq parmijana", desc: "Pishloq ostida pishirilgan qarsildoq tovuq, fri va salat.", price: 79000, img: "img/m/parmigiana.jpg", time: 20 },
    { id: "h9", cat: "hot", name: "Rikottali tovuq rulet", desc: "Rikotta to'ldirilgan tovuq to'shi va kartoshka pyuresi.", price: 72000, img: "img/m/frango.jpg", time: 22 },
    { id: "i1", cat: "milliy", name: "To'y oshi", desc: "Devzira guruch, qo'y go'shti, sariq sabzi, no'xat va mayiz.", price: 45000, emoji: "🍛", img: "", popular: true, time: 10, variants: [{ id: "half", name: "0,5 porsiya", price: 28000 }, { id: "full", name: "1 porsiya", price: 45000 }], extras: [{ id: "egg", name: "Bedana tuxum", price: 5000 }, { id: "qazi", name: "Qazi", price: 15000 }] },
    { id: "m1", cat: "milliy", name: "Buzoq go'shti jarkop", desc: "Dimlangan sabzavotlar va ko'katlar bilan buzoq go'shti.", price: 69000, img: "img/m/veal-stew.jpg", popular: true, time: 25, weight: "400 g" },
    { id: "i3", cat: "milliy", name: "Lag'mon", desc: "Qo'lda cho'zilgan xamir, mol go'shti va sabzavotlar.", price: 38000, emoji: "🍜", img: "", time: 15, variants: [{ id: "half", name: "0,5 porsiya", price: 24000 }, { id: "full", name: "1 porsiya", price: 38000 }] },
    { id: "i2", cat: "milliy", name: "Manti", desc: "Bug'da pishirilgan, qo'y go'shti va piyozli. 5 dona.", price: 35000, emoji: "🥟", img: "", time: 20 },
    { id: "i14", cat: "milliy", name: "Somsa", desc: "Tandirda pishgan, go'shtli. 1 dona.", price: 9000, emoji: "🥐", img: "", time: 5 },
    { id: "p1", cat: "pasta", name: "Qo'ziqorinli rizotto", desc: "Arborio guruch, yangi qo'ziqorinlar, oq vino va parmezan.", price: 75000, img: "img/m/risotto.jpg", time: 20 },
    { id: "p2", cat: "pasta", name: "Nyokki", desc: "Uy nyokkisi, qaymoqli sous va muskat yong'og'i.", price: 69000, img: "img/m/gnocchi.jpg", time: 15 },
    { id: "p3", cat: "pasta", name: "Baqlajonli lazanya", desc: "Baqlajon, uy sousi va bri pishlog'i.", price: 72000, img: "img/m/lasagna.jpg", time: 20 },
    { id: "s1", cat: "salad", name: "Sunomono", desc: "Kunjutli bodring, shirin-nordon sous.", price: 32000, img: "img/m/sunomono.jpg", time: 7 },
    { id: "s2", cat: "salad", name: "Bahor salati", desc: "Yangi sabzavotlar, rukola va limonli zaytun moyi.", price: 39000, img: "img/m/salad2.jpg", popular: true, time: 8 },
    { id: "s3", cat: "salad", name: "Shef salati", desc: "Mavsumiy sabzavotlar va maxsus sous.", price: 45000, img: "img/m/gourmet.jpg", time: 10 },
    { id: "u1", cat: "sushi", name: "Black roll", desc: "Guruch, nori, qaymoqli pishloq, ilon baliq, bodring, qora ikra.", price: 89000, img: "img/m/black-roll.jpg", popular: true, time: 15, weight: "8 dona" },
    { id: "u2", cat: "sushi", name: "Ebi krab", desc: "Panirovkadagi krevetka, qor krabi, ko'k piyoz, achchiq sous.", price: 95000, img: "img/m/ebi-crab.jpg", time: 15, weight: "8 dona" },
    { id: "u3", cat: "sushi", name: "Filadelfiya avokado bilan", desc: "Guruch, nori, qaymoqli pishloq, gulmohi, avokado, bodring.", price: 92000, img: "img/m/philadelphia.jpg", time: 15, weight: "8 dona" },
    { id: "u4", cat: "sushi", name: "Nigiri losos", desc: "Oddiylik ichidagi mukammallik. 2 dona.", price: 42000, img: "img/m/nigiri-salmon.jpg", time: 8 },
    { id: "u5", cat: "sushi", name: "Nigiri tunets", desc: "Tunets, ko'k piyoz va limon. 2 dona.", price: 48000, img: "img/m/nigiri-tuna.jpg", time: 8 },
    { id: "u6", cat: "sushi", name: "Yokohama set", desc: "Shefdan nigiri assorti. 8 dona.", price: 145000, img: "img/m/yokohama.jpg", time: 20 },
    { id: "r1", cat: "ramen", name: "Shoyu ramen", desc: "Mol go'shti sho'rvasi, tuxum va ko'katlar.", price: 65000, img: "img/m/ramen3.jpg", popular: true, time: 15, extras: [{ id: "egg", name: "Qo'shimcha tuxum", price: 6000 }, { id: "noodle", name: "Qo'shimcha lapsha", price: 10000 }, { id: "chili", name: "Achchiq yog'", price: 3000 }] },
    { id: "r2", cat: "ramen", name: "Miso ramen", desc: "Miso sho'rva, go'sht, tuxum va bambuk.", price: 62000, img: "img/m/ramen2.jpg", time: 15 },
    { id: "r3", cat: "ramen", name: "Tovuqli ramen", desc: "Tovuq sho'rvasi, ko'k piyoz va kunjut.", price: 55000, img: "img/m/ramen1.jpg", time: 12 },
    { id: "d1", cat: "dessert", name: "Shokoladli tort", desc: "Qatlamli shokolad, yong'oq va malinali sous.", price: 42000, img: "img/m/dessert2.jpg", popular: true, time: 5 },
    { id: "d2", cat: "dessert", name: "Malinali granita", desc: "Pishgan sut, greyfrut va dolchin.", price: 38000, img: "img/m/dessert.jpg", time: 5 },
    { id: "i18", cat: "dessert", name: "Chak-chak", desc: "Asal va yong'oq bilan.", price: 20000, emoji: "🍯", img: "", time: 2 },
    { id: "c1", cat: "cocktail", name: "Negroni", desc: "Jin, qizil vermut va bitter. Klassika.", price: 85000, img: "img/m/negroni.jpg", popular: true, time: 5, weight: "120 ml" },
    { id: "c2", cat: "cocktail", name: "Aperol Spritz", desc: "Aperol, prosekko va soda, apelsin bo'lagi bilan.", price: 79000, img: "img/m/aperol.jpg", time: 4, weight: "250 ml" },
    { id: "c3", cat: "cocktail", name: "Margarita", desc: "Tekila, apelsin likyori va laym sharbati.", price: 82000, img: "img/m/margarita.jpg", time: 4, weight: "150 ml" },
    { id: "c4", cat: "cocktail", name: "Old Fashioned", desc: "Burbon, bitter, olxo'ri va tarxun.", price: 92000, img: "img/m/secret-cocktail.jpg", time: 5, weight: "100 ml" },
    { id: "c5", cat: "cocktail", name: "Mojito", desc: "Rom, yalpiz, laym va soda. Alkogolsiz varianti ham bor.", price: 69000, img: "img/m/mojito.jpg", time: 4, weight: "300 ml", variants: [{ id: "alc", name: "Alkogolli", price: 69000 }, { id: "zero", name: "Alkogolsiz", price: 45000 }] },
    { id: "w1", cat: "wine", name: "Valpolicella Classico", desc: "Qizil quruq, Italiya. Korvina, Rondinella. 13,4%.", price: 420000, img: "img/m/valpolicella.jpg", time: 2, weight: "0,75 l", fit: "contain" },
    { id: "w2", cat: "wine", name: "Amarone della Valpolicella", desc: "Qizil quruq, Italiya. Ov go'shti va pishloqlarga. 15,8%.", price: 980000, img: "img/m/amarone.jpg", popular: true, time: 2, weight: "0,75 l", fit: "contain" },
    { id: "w3", cat: "wine", name: "Qizil vino, bokal", desc: "Somelyedan kun vinosi.", price: 65000, img: "img/m/wine-hand.jpg", time: 1, weight: "150 ml" },
    { id: "w4", cat: "wine", name: "Oq vino, bokal", desc: "Salqin oq quruq vino.", price: 65000, img: "img/m/wine-white.jpg", time: 1, weight: "150 ml" },
    { id: "i15", cat: "drinks", name: "Ko'k choy", desc: "Choynakda, 1 litr.", price: 8000, emoji: "🫖", img: "", time: 2 },
    { id: "i16", cat: "drinks", name: "Limonli qora choy", desc: "Choynakda, 1 litr.", price: 12000, emoji: "🍋", img: "", time: 2 },
    { id: "i17", cat: "drinks", name: "Kompot", desc: "Uy kompoti, 1 litr.", price: 15000, emoji: "🥤", img: "", time: 1 }
  ],
  waiters: [
    { id: "w1", first: "Aziz", last: "Karimov", pin: "1111" },
    { id: "w2", first: "Dilnoza", last: "Rahimova", pin: "2222" },
    { id: "w3", first: "Jasur", last: "Toshmatov", pin: "3333" }
  ],
  tables: [
    { id: "t1", no: "1", zone: "Zal", seats: 4, waiterId: "w1" },
    { id: "t2", no: "2", zone: "Zal", seats: 4, waiterId: "w1" },
    { id: "t3", no: "3", zone: "Zal", seats: 6, waiterId: "w1" },
    { id: "t4", no: "4", zone: "Zal", seats: 4, waiterId: "w2" },
    { id: "t5", no: "5", zone: "Zal", seats: 2, waiterId: "w2" },
    { id: "t6", no: "6", zone: "Zal", seats: 8, waiterId: "w2" },
    { id: "t7", no: "7", zone: "Ayvon", seats: 6, waiterId: "w3" },
    { id: "t8", no: "8", zone: "Ayvon", seats: 6, waiterId: "w3" },
    { id: "t9", no: "VIP-1", zone: "VIP xona", seats: 12, waiterId: "w3" }
  ],
  kitchenPin: ""
};
